### PR TITLE
[WEEX-434][iOS] fix the input cannot move down to original position a…

### PR DESCRIPTION
**Pull request by ha1o0**
fix the input cannot move down to original position and the toolbar of keyboard cover the input component when on bottom

### CODE REVIEW

**Comment by wqyfavor** [comment]
Please provide the page source. I put an edit at the bottom of a page but cannot reproduce this issue. @weifengsmile

**Comment by weifengsmile** [comment]
```
<template>
  <div class="wrapper">
    <text class="greeting">The environment is ready!</text>
    <input type="text" placeholder="Input Text" class="input" value=""/>
  </div>
</template>

<script>
export default {
  name: 'App',
  data () {
    return {
    }
  }
}
</script>

<style scoped>
.input {
    background-color: #ffffff;
    margin-top: 300px;
    width: 300px;
    height: 80px ;
    padding: 20px;
    color: #000000;
  }
  .wrapper {
    justify-content: center;
    align-items: center;
    background-color: #888888;
  }
  .greeting {
    text-align: center;
    margin-top: 70px;
    font-size: 50px;
    color: #41B883;
  }
</style>
```
code

It is very simple. You can check the image:
init page
the input component focus
the keyboard dismiss

**Issue 1: The WXRootView cannot reset to original position.**
**Issue 2: The keyboards cover a apart of the input component.**

@wqyfavor

**Comment by wqyfavor** [comment]
I cannot reproduce with your source code using playground. What iOS version are you using. Why there is no navigation bar in you picture.

**Comment by weifengsmile** [comment]
iOS 11.1, and the weexSDK version is the latest version in pods. I didn't use the playground app, this is the result from iOS simulator, and there is the same issue in real device.

**Comment by wqyfavor** [comment]
Please provide your xcode project. I really cannot reproduce. I don't know the differences between playground and your app. Or you may use playground or Taobao app to scan your bundle and to see if this issue can reproduce. @weifengsmile

**Comment by weifengsmile** [comment]
This is the iOS xcode project:
[ios-issue.zip](https://github.com/apache/incubator-weex/files/2137558/ios-issue.zip)
And this issue can not be reproduced in the playground, it is different from simulator and real device.
You can try it in simulator or real device. @wqyfavor

**Comment by wqyfavor** [comment]
@weifengsmile Please close your PR. I created another one and is a little different from yours. https://github.com/apache/incubator-weex/pull/1297

Your fix cannot work in Playground. So I add 20px to offset directly.

**Comment by weifengsmile** [comment]
ok, but you should pay attention to the different offset between iOS 10 and iOS 11, and there is also different offset between iPhone X and other iPhones. @wqyfavor

**Pull request closed without merging**
