### PR TITLE
[iOS] Make sure gesture recognizers won't be lost.

### PR DESCRIPTION
**Pull request by AntiMoron**
First of all, thank you for your contribution! 

Please makes sure that these checkboxes are checked before submitting your PR, thank you!

CheckList:

**if** *isBugFix* **:**

  * [x] Make sure that you add at least one unit test for the bug which you had fixed.

**elif** *isNewFeature* **:**

  * [ ] Update API docs for the component.
  * [ ] Update/Add demo to demonstrate new feature.
  * [ ] Update test scripts for the feature.
  * [ ] Add unit tests for the feature.

### CODE REVIEW

**Comment by AntiMoron** [comment]
Here's the issue.

weexsmall

On bounce triggered, gesture recognizers of cells outside screen are lost in the gif.

**Comment by cxfeng1** [comment]
@AntiMoron  Can you provide the demo? http://dotwe.org/vue/

**Comment by AntiMoron** [comment]
@cxfeng1  No,  customized weex component is involved. I can send you the demo.

**Comment by acton393** [comment]
hi @AntiMoron  I highly recommend you add your gesture in `ViewDidLoad` method, which is the component lifecycle,  if the component is child of list, it will be re-used, actually it will be set as nil, and when it come to appear , then `loadView` lifecycle called again, and this tip I will mention it in our documentation later,  so there is no need to reserve view's `gesture recognizer`.

**Pull request closed without merging**
