### PR TITLE
Fix bad link

### PR DESCRIPTION
**Pull request by W4anD0eR96**
By an aggressive way

### CODE REVIEW

**Comment by Hanks10100** [comment]
Thanks for your contribution, but the source code of Weex's website has moved to https://github.com/apache/incubator-weex-site . The `doc/` here will be removed when the new website is ready.

**Comment by W4anD0eR96** [comment]
co apache/incubator-weex-site#22

you can close this PR if it's better to be.

**Comment by Hanks10100** [comment]
@W4anD0eR96 I can't close it, only you can close it on GitHub.

**Comment by W4anD0eR96** [comment]
@Hanks10100 Oops, I thought you had commit bits of this repo :stuck_out_tongue_closed_eyes:

I'll leave it open until apache/incubator-weex-site#22 be resolved

**Pull request closed without merging**
