### PR TITLE
refine code structure for eagle

### PR DESCRIPTION
**Pull request by jianhan-he**

### CODE REVIEW

**Comment by cnryb** [comment]
The Travis CI build failed, can you fix it ?

**Comment by YorkShen** [comment]
@jianhan-he Wait a minute, maybe we could solve it togehter.

**Comment by YorkShen** [comment]
It works well now, there is some network problem between the server of TravisCI and Maven repo.

**Comment by chenzefeng09** [comment]
What is eagle ?

**Comment by YorkShen** [comment]
A C++ implementation of `Vue.js`, and they are trying to decouple the existing interface to a new repo.

**Pull request merged**
