### PR TITLE
[WEEX-475] fix Weex list component in the Android without scroll bars

### PR DESCRIPTION
**Pull request by aixiaoxiang**
fix Weex list component in the Android without scroll bars

---
fix  before
  
41773666-742f69b6-764f-11e8-8d4d-3746880431f8 2

---
fix after

image

### CODE REVIEW

**Comment by gubaojian** [comment]
use showScrollbar = false

**Comment by aixiaoxianggithub** [comment]
@gubaojian 

I want to display scroll bars。

in Android

use  showScrollbar = true,  Cannot scroll bars are displayed。

Such as：
http://dotwe.org/vue/76fc6c84ddf78be0888f3826458fa67a

**Comment by aixiaoxianggithub** [comment]
@gubaojian 

https://github.com/apache/incubator-weex/pull/1287#issuecomment-405434048

**Comment by YorkShen** [comment]
I think that disabled scroll bar in Android is a feature, not a bug. If `showScrollbar = true` doesn't works for you, please fire a issue instead.

**Comment by aixiaoxiang** [comment]
@YorkShen 在安卓上不是想禁用滚动条，而是设置了showScrollbar=true，也不显示滚动条. 在安卓上list怎么设置都不显示滚动条

**Comment by aixiaoxiang** [comment]
@YorkShen 在安卓上不是想禁用滚动条，而是设置了showScrollbar=true，也不显示滚动条. 在安卓上list怎么设置都不显示滚动条

**Comment by YorkShen** [comment]
If this is your case, fire another issue, please.

**Comment by zhangxiang0316** [comment]
请问作者这个问题解决了吗，我的也是不显示滚动条，你是怎么解决的？

**Pull request closed without merging**
