### PR TITLE
+ [android] support "word-break" style in text

### PR DESCRIPTION
**Pull request by Yanjiie**
* Support "word-break" style in text. Can use "break-word" or "break-all".

### CODE REVIEW

**Comment by misakuo** [comment]
Great! very useful feature. Thanks for your contribution

**Comment by misakuo** [comment]
@acton393 Does iOS support the `word-break` style now?

**Comment by sunsky6** [comment]
It seem like iOS doesn't support `word-break`. I can support this later.

**Comment by gubaojian** [comment]
great work

**Comment by gubaojian** [comment]
please provide one or more testcase on  http://dotwe.org/vue

**Comment by sunsky6** [comment]
Hey ~ @misakuo @gubaojian 
This is a testcase -- [Word-Break](http://dotwe.org/vue/f5011e3908f4f4ab3b854bc5b990b880).
I found iOS doesn't support `word-break` style, but the default way is `break-all`.
I will create a new pull request later, then try to support it.
Thx you both.

**Pull request closed without merging**
