### PR TITLE
[Feature] Support Android R

### PR DESCRIPTION
**Pull request by katherine95s**
# Brief Description of the PR

# Checklist
* Demo:
* Documentation:

### CODE REVIEW

**Review by YorkShen — APPROVED** [review]
LGTM

**Comment by chenzefeng09** [comment]
编译报错
 /Users/chenzefeng/Development/incubator-weex/android/sdk/src/legacyRelease/cpp/Source/android/multiprocess/weex_js_connection.cpp:653:33: error: use of undeclared identifier '__ANDROID_API_P__'
    if (SoUtils::android_api() <= __ANDROID_API_P__) {
                                  ^
  1 error generated.
  ninja: build stopped: subcommand failed.

**Comment by katherine95s** [comment]
> 编译报错
> /Users/chenzefeng/Development/incubator-weex/android/sdk/src/legacyRelease/cpp/Source/android/multiprocess/weex_js_connection.cpp:653:33: error: use of undeclared identifier '**ANDROID_API_P**'
> if (SoUtils::android_api() <= **ANDROID_API_P**) {
> ^
> 1 error generated.
> ninja: build stopped: subcommand failed.

应该是ndk环境问题，ndk版本为18

**Comment by xdmaolei** [comment]
May I ask why remove JavaScript Log？

**Pull request merged**
