### PR TITLE
* [doc] doc example: delete <text> props “lines”

### PR DESCRIPTION
**Pull request by SimplyY**
`<text>` component props “lines” is invalid, so I delete “lines=3” in all doc files.

weex playgroud demo（which proved what I said）: http://dotwe.org/vue/5ac8c3970d049c1c0b41c4ef9a103963

### CODE REVIEW

**Comment by acton393** [comment]
hi @SimplyY 
It looks like `lines` property is useless on your case , but I remember it can be used to limit characters into 1 row and ellipse in text.

your case should take into consideration, support lines applied when text drawing

**Comment by SimplyY** [comment]
http://dotwe.org/vue/b1825c31715032e000492290e94a2281

look this.

only 'useCss' class（lines in css） is work, lines props is still not work.

**Comment by SimplyY** [comment]
@acton393

**Comment by Hanks10100** [comment]
Just remind you that, the website and documents have been moved to the [incubator-weex-site](https://github.com/apache/incubator-weex-site) repo. The `doc` folder here has already been removed. Please refer to #993 .

**Pull request closed without merging**
