### PR TITLE
Wrong a word in the documentation

### PR DESCRIPTION
**Pull request by ulivz**
This sentence：

> 这部分成本会**承**下降和收敛的趋势。

should be changed to：

> 这部分成本会**呈**下降和收敛的趋势。

### CODE REVIEW

**Comment by toxichl** [comment]
Why still can not pass, I just modified a word？

**Comment by sospartan** [comment]
@toxichl sorry the CI is broken, I'll fix that soon.

**Comment by gurisxie** [comment]
@ulivz I'm sorry for that I can't found what a repository need been pulled.Can you close this pr [here](https://github.com/apache/incubator-weex/pull/260). If you have new change for weex,hope your new pull request.Thanks a lot!

**Comment by Hanks10100** [comment]
The CI is broken and the PR have no response for a long time. I'll close it shortly. If there still need further discussions about it, you could open a new pull request.

Thanks for your cooperation.

**Pull request closed without merging**
