### PR TITLE
+ [android] fix wrong vertical offset on waterfall

### PR DESCRIPTION
**Pull request by misakuo**
The `RecyclerView#computeVerticalScrollOffset()` will return wrong value when use `StaggeredGridLayoutManager`, add property `stable` to control calculated vertical offset using accumulative `dy` 
Property `stable` only effective on android, and will not be public in the document

Reference: https://issues.apache.org/jira/browse/WEEX-39

### CODE REVIEW

**Comment by sospartan** [comment]
Pls create a JIRA issue about this. And rebase your branch will fix the travis error.

**Comment by misakuo** [comment]
@sospartan done~

**Comment by sospartan** [comment]
@misakuo Pls resolve the conflicting files here.

**Comment by misakuo** [comment]
@sospartan completed ；）

**Pull request merged**
